### ISSUE TITLE
Documentation about Kinect v2 internals?

### ISSUE THREAD

**Issue by floe** [Kinect/Docs#17]
Hey everyone,

first of all, thanks for your work! I'm one of the maintainers of the libfreenect2 open-source library for the Kinect v2, and I was wondering: since Microsoft policy seems to be shifting towards a more open stance, would it be possible to release protocol documentation etc. for the Kinect v2 at some point? Would help us a lot to clear up some leftover issues :-)

Best, Florian

**Comment by floe** [comment]
Any comments?

**Comment by ChimeraScorn** [comment]
Thank you for the request.  At this time, we do not have anything to share, but we may at some point in the future. :) Sorry to not be able to provide a more definitive answer at this time.

**Comment by floe** [comment]
Thanks! A bit non-committal, but I'll keep hoping ;-)

**Comment by ChimeraScorn** [comment]
Hope springs eternal. :)  If this changes, I'll be sure to let you know.
